name: Build and Release
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: 设置Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.5
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: 打包
      run: |
        python build.py \
        --app_name "Tubev" \
        --version "0.0.1" \
        --spec_file "main.spec" \
        --entitlements "entitlements.plist" \
        --provisioning_profile "tubev_provision.provisionprofile" \
        --app_certificate "3rd Party Mac Developer Application: John Smith (L42TK32G7A)" \
        --installer_certificate "3rd Party Mac Developer Installer: John Smith (L42TK32G7A)" \
        --output_dir "dist"
    # - name: 上传打包文件
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     upload_url: ${{ github.event.release.upload_url }}
    #     asset_path: ./dist/your_script
    #     asset_name: your_script_macos
    #     asset_content_type: application/octet-stream
